package edu.vu.isis.ammoui.util;

public interface DefaultPrefs {
    
    String MULTICAST_IP = "228.10.10.90";
    int MULTICAST_PORT = 9982;
    int MULTICAST_NET_TIMEOUT = 1000;
    int MULTICAST_CONN_IDLE_TIMEOUT = 3000;
    int MULTICAST_TIME_TO_LIVE = 10;
    
    String RELIABLE_MULTICAST_IP = "228.8.8.8";
    int RELIABLE_MULTICAST_PORT = 45588;
    int RELIABLE_MULTICAST_NET_TIMEOUT = 1000;
    int RELIABLE_MULTICAST_CONN_IDLE_TIMEOUT = 3000;
    int RELIABLE_MULTICAST_TIME_TO_LIVE = 8;
    int RELIABLE_MULTICAST_FRAG_DELAY = 0;
    
    String GATEWAY_IP = "129.59.129.191";
    int GATEWAY_PORT = 33289;
    int GATEWAY_NET_CONN_TIMEOUT = 1000;
    int GATEWAY_CONN_IDLE_TIMEOUT = 3000;
    
    String SERIAL_DEVICE = "/dev/ttvUSB0";
    int SERIAL_BAUD_RATE = 9600;
    int SERIAL_SLOT_NUMBER = 8;
    int SERIAL_RADIOS_IN_GROUP = 16;
    int SERIAL_SLOT_DURATION = 750;
    int SERIAL_TRANSMIT_DURATION = 500;

}
